# -*- coding: utf-8 -*-
"""
Corpus for the admissions-essay AI detector.

IMPORTANT / HONESTY NOTE (see also the project report):
This sandbox has no internet access, so this corpus could not be scraped
or pulled from an existing dataset. Every essay below was written for this
project to *stand in* for two populations:

  HUMAN_TRAIN / HUMAN_TEST  - short personal-statement-style essays written
                               to imitate genuine, imperfect student prose:
                               uneven sentence length, concrete specific
                               detail, occasional fragments, informal voice.

  AI_TRAIN / AI_TEST        - essays deliberately written in the *formulaic*
                               register that current LLMs fall into on this
                               task when asked for a polished admissions
                               essay: hedged claims, triadic lists, stock
                               transitions ("Moreover", "It is important to
                               note"), uniform sentence length, generic
                               uplifting closers, elevated near-synonyms
                               ("delve", "underscore", "testament",
                               "tapestry", "boundless").

  ESL_TEST                  - short essays written to imitate a genuinely
                               common human population: fluent but
                               non-native English writers, who often produce
                               simpler, more repetitive sentence structure.
                               This set exists specifically to check whether
                               the detector mistakes "simple and repetitive"
                               for "machine-written" (a documented failure
                               mode of real AI detectors).

  MIXED_DEMO                - one essay with a human first half and an
                               AI-polished second half, used as the default
                               text in the app so the sentence-level
                               highlighting has something real to show.

This is a small, synthetic, single-author (well, single-model) corpus. It is
not a substitute for a real dataset scraped from many writers and many
models, and the report is explicit about what that means for how much to
trust the numbers below.
"""

HUMAN_TRAIN = [
"""My grandmother taught me to cook the summer I turned twelve, mostly because she got tired of me hovering in the kitchen doorway asking what everything was. We made pierogi from scratch, and I remember the dough sticking to everything, my hands, the counter, even the dog's nose when he wandered too close. She didn't measure anything. When I asked how much flour, she just said "enough," and somehow that was an answer. I burned the first batch of onions so badly the smoke alarm went off twice. She laughed, opened a window, and started over without a word of complaint. That's the thing about her kitchen: mistakes were just part of the recipe, never a reason to stop.""",

"""I lost the regional debate final by one point, on a technicality about rebuttal timing that I still think was called wrong. For about a week I was furious about it, replaying the round in my head on the bus, in the shower, during math class. Then my coach asked me a question that annoyed me at the time: "What would you do differently if the score didn't matter?" I didn't have a good answer, which bothered me more than the loss did. So I went back and rewatched the recording, and I noticed I'd rushed my closing argument because I was scared of running out of time. That's a fixable problem. The score wasn't.""",

"""Our town's only movie theater closed the spring of my sophomore year, and honestly I didn't think much of it at first. Then I noticed my after-school routine had a hole in it. A few of us started a "movie night" in Dana's garage instead, projector taped to a bedsheet, folding chairs from three different houses. It was worse in almost every technical way. The sound cut out during the scary parts. But somehow more people showed up each week, kids I barely knew from other grades, because it turned out what we missed wasn't really the theater, it was having somewhere to be on a Friday.""",

"""I work weekends at my uncle's auto shop, mostly doing oil changes and tire rotations, occasionally handed something harder when he's short-staffed. Last winter a woman brought in her car making a noise she described as "like a dying bird, but angrier." I had no idea what that meant mechanically, and neither did my uncle at first. Turned out to be a loose heat shield rattling against the exhaust, a two-minute fix once we found it, forty minutes to find it. I liked that more than I expected to, the part where the answer isn't obvious and you have to actually listen for it.""",

"""My little brother has a stutter, and for years I was the sibling who finished his sentences for him, thinking I was helping. A speech therapist eventually pulled me aside and told me, pretty bluntly, that I wasn't. She said every time I jumped in, I was telling him his own voice wasn't worth waiting for. I felt awful, honestly, and a little defensive. But I started counting to five in my head before saying anything when he talked. Some days that's still hard. He talks more now, though, and slower, and I've learned that silence isn't the same thing as a problem.""",

"""Three summers of detasseling corn taught me more about heat than any thermometer could. You start at five in the morning to beat it, walking the rows before the sun is fully up, and by ten your shirt is soaked through and you still have six hours left. I complained constantly the first summer. By the third, I'd figured out which rows had shade at which hour, how to pace myself so I didn't crash by noon, small things nobody teaches you, you just learn them by getting it wrong enough times. My dad still does this work every summer. I understand him a little better now than I used to.""",

"""I didn't get into the honors chemistry track sophomore year, which stung more than I expected given that I'm not even sure I like chemistry. I emailed the teacher asking what I could do differently, half expecting a form response. Instead she wrote back three paragraphs, and one line stuck with me: "You're strong on the math, weak on writing up your reasoning, and that's the actual skill this class tests." I hadn't thought of lab reports as a writing skill before. I started treating them that way, badly at first, and by spring I'd talked my way into the class after all, on the strength of one very over-explained report on reaction rates.""",

"""My family moved four times before I turned ten, which people usually assume made me an easy talker, good at meeting people fast. It did the opposite, actually. I got tired of investing in friendships that had an expiration date I couldn't control, so by the third move I mostly kept to myself. It took a teacher noticing I ate lunch alone every day for a semester before I really opened up again, and even then it was slow, a few words at a time. I'm better at it now, but I still remember exactly which of my current friends I decided, consciously, to let myself get attached to.""",

"""The community garden plot behind the library was mostly weeds when four of us took it over freshman year. None of us knew anything about growing vegetables. We killed the first round of tomatoes by overwatering them, which felt impossible given how dry the soil looked on top. An older woman who tended the plot next to ours eventually took pity on us and explained soil drainage in a way that finally made sense, with her hands more than her words, really, pushing a finger into the dirt to show us what "too wet" actually felt like. We got real tomatoes the second year. I still don't consider myself good at gardening, but I know what wet dirt is supposed to feel like now, which is apparently most of the battle.""",

"""I've kept the same paper journal since eighth grade, not because I'm disciplined about it, I'm really not, some months go by with nothing, but because I like having a record of what I actually thought at the time instead of what I remember thinking. Reading back through it is occasionally mortifying. Freshman year me had extremely strong opinions about a boy band that fourteen-year-old me apparently thought were going to matter. But it's also useful. I can see, in writing, exactly when I stopped being scared of public speaking, which was one specific Tuesday in tenth grade, not a gradual thing at all like I would have guessed.""",

"""My part-time job is answering phones at a veterinary clinic, which sounds calm and is almost never calm. People call in a genuine panic about their dogs eating socks, chocolate, once memorably an entire bar of soap. I used to just transfer everything straight to the vet tech, overwhelmed by how upset people got over what was often, medically, not that serious. Six months in I can usually tell from the first thirty seconds whether it's an emergency or just a scared owner who needs someone calm on the other end of the line. Mostly it's the second one. Being that calm voice turned out to be its own kind of useful.""",

"""I ran track for two years before I actually got fast, and honestly the two facts might not be related. I was fast the same season I stopped caring so much about being fast, which is annoying advice to give anyone but happens to be true in my case. Before that I'd tighten up before every race, overthink my start, false-start twice in one meet out of pure nerves. My coach eventually told me to stop watching the clock during practice entirely for a month. It felt like giving something up. My times dropped anyway, which I still don't fully understand, but I've stopped arguing with it.""",

"""My grandfather doesn't talk much about the war, and for a long time I didn't ask, assuming it was a closed subject. Then last year, helping him clean out the garage, I found a box of letters he'd written to my grandmother during that time, and he let me read a few. They were nothing like I expected, mostly about food he missed and a dog he'd had before, small ordinary things, not the big dramatic moments I'd imagined. I asked him about it afterward and he just said, "that's what you think about, actually, when the big stuff is too much." I think about that a lot now.""",

"""Sophomore year I signed up for the school's peer tutoring program mostly because I needed volunteer hours, not out of any noble instinct. My first student was a sixth grader who hated math with a real, specific intensity, and for the first few sessions I genuinely could not get through to him. I tried three different explanations of fractions before one, involving pizza slices and his little sister's greed about them, finally landed. He still doesn't love math. But he stopped crying during our sessions, which felt like an actual accomplishment at the time, and honestly still does.""",

"""I've worked the register at my family's restaurant since I was old enough to reach it, which means I've watched a lot of first dates go badly. There's a specific silence that means it's not working out, different from the comfortable kind. I started, without really meaning to, timing my visits to the table around those silences, coming by with water refills right when a conversation needed rescuing. My dad noticed and started calling it "customer service," which felt generous. I just didn't like watching people be awkward in my family's restaurant. Turns out that's most of what customer service is anyway.""",

"""My school cut the art program the same year I'd finally saved up for a decent set of paints, which felt like extremely bad timing, though I know that's not really how budget decisions work. A few of us petitioned to keep at least the after-school club running, unpaid, in a spare classroom, and the vice principal agreed mostly, I think, to make us stop emailing him. It's a smaller thing than a real program. We meet twice a week, no curriculum, whoever wants to teach something that week just does. I've learned more there, somehow, than I did in the class it replaced, though I'd still take the funding back if I could.""",

"""I spent a summer teaching my little cousin to swim, which I agreed to before realizing I'm not actually a strong swimmer myself, just stronger than a six-year-old. She was terrified of putting her face in the water, would grip the pool ladder like it owed her money. What finally worked wasn't any technique I'd read about, it was letting her hold onto me instead of the ladder for the first two weeks, just so she'd trust that going under wasn't the same as drowning. By August she was doing laps, badly, arms everywhere, but laps. I don't think I taught her to swim so much as I taught her to stop being scared long enough to figure it out herself.""",

"""My debate partner and I disagree about almost everything outside of debate, politics, music, where to eat before tournaments, and I think that's exactly why we won as often as we did. She'd build an argument I hadn't considered because she genuinely believed a version of the other side, not as a exercise, actually believed it, and I'd have to actually engage with it instead of just performing disagreement. Most of our best rounds came out of arguments we'd already half-had with each other in the car on the way to the tournament. I don't know that I'd have gotten as good working with someone who agreed with me more.""",

"""I broke my arm the week before regional swim finals, which is about the least convenient possible timing an injury can have, and spent the next six weeks on deck instead of in the water, timing splits for the teammates who could actually swim. It was miserable at first, standing there with a stopwatch while everyone else did the thing I'd trained for all year. But watching that closely, from outside the water instead of in it, I noticed technical mistakes in my own stroke I'd never caught on video, small stuff about my hip rotation. I came back slower than before the injury and somehow swam a faster time than I ever had, three months later, for reasons I'm still not sure I fully understand.""",

"""My neighbor is ninety-one and still mows his own lawn, refuses help on principle as far as I can tell. Last spring I started "accidentally" leaving my mower out where he'd see it, hoping he'd take the hint that borrowing it was easier than hauling his own out of the shed. He never took the bait. Eventually I just started showing up on Saturdays to help, framing it as wanting company, which wasn't entirely a lie. He tells the same three stories every time, almost word for word, and I've started to look forward to which one it'll be that week.""",
]

AI_TRAIN = [
"""From a young age, I have always been deeply passionate about learning and growth. Throughout my academic journey, I have consistently sought out opportunities to challenge myself and expand my horizons. Whether in the classroom or beyond it, I have strived to embody the values of curiosity, resilience, and integrity. Moreover, my experiences have taught me the importance of perseverance in the face of adversity. Every challenge I have encountered has served as a stepping stone toward personal growth. As I look toward the future, I am filled with excitement and determination to continue this journey of self-discovery, armed with the lessons I have learned and the passion that drives me forward.""",

"""Volunteering at the local shelter was, without question, one of the most transformative experiences of my life. It taught me not just the value of compassion, but also the importance of humility and service to others. Each interaction I had with the residents underscored the profound impact that small acts of kindness can have on a person's life. Furthermore, this experience deepened my understanding of community and belonging. It is important to note that volunteering is not simply about giving back; it is about forging genuine connections that enrich both parties involved. This experience has left an indelible mark on my character and continues to shape the person I strive to become.""",

"""Throughout my high school career, I have consistently pursued excellence in both academics and extracurricular activities. From leading my school's robotics team to volunteering at community events, I have sought to make a meaningful difference wherever possible. These experiences have not only honed my leadership skills but also instilled in me a deep sense of responsibility. Additionally, they have taught me the value of collaboration and teamwork. It is through these challenges that I have grown as an individual, developing resilience and adaptability that will undoubtedly serve me well in college and beyond. I am eager to bring this same passion and dedication to my future academic pursuits.""",

"""My passion for environmental sustainability began in middle school, when I first learned about the devastating effects of climate change. Since then, I have dedicated myself to raising awareness and driving meaningful change within my community. Whether organizing recycling initiatives or educating my peers about renewable energy, I have consistently sought to make a tangible difference. Moreover, this passion has taught me invaluable lessons about leadership, perseverance, and the power of collective action. It is a testament to what can be achieved when individuals come together for a common cause. As I continue this journey, I remain committed to becoming a catalyst for positive environmental change, both locally and globally.""",

"""Music has always been an integral part of my identity, shaping who I am both as an individual and as a member of my community. From an early age, I discovered a profound connection to the piano, one that has only deepened over the years. Through countless hours of practice and dedication, I have not only honed my technical skills but also cultivated a deep appreciation for discipline and perseverance. Furthermore, music has taught me the importance of creativity and self-expression, values that I carry with me in all aspects of my life. This journey has been nothing short of transformative, and I look forward to continuing to explore the boundless possibilities that music offers.""",

"""As captain of my school's debate team, I have had the privilege of developing not only my public speaking skills but also my ability to think critically under pressure. This role has taught me the importance of preparation, adaptability, and effective communication. Moreover, it has underscored the value of empathy in understanding differing perspectives, a skill that has proven invaluable both in competition and in life. Through countless hours of research and practice, I have learned that true leadership is not about having all the answers, but about empowering others to find their own voices. This experience has profoundly shaped my aspirations for the future.""",

"""My internship at a local biotechnology firm opened my eyes to the boundless possibilities within scientific research. Working alongside experienced researchers, I gained hands-on experience in laboratory techniques while also learning the value of meticulous attention to detail. This experience underscored the importance of collaboration in achieving scientific breakthroughs, as well as the necessity of resilience when experiments do not go as planned. Furthermore, it solidified my passion for pursuing a career in the sciences, one dedicated to making meaningful contributions to the field. I am eager to continue building on this foundation as I embark on the next chapter of my academic journey.""",

"""Growing up in a multicultural household has profoundly shaped my worldview and instilled in me a deep appreciation for diversity. Navigating between different cultural traditions taught me valuable lessons about adaptability, empathy, and open-mindedness. Moreover, this unique upbringing has equipped me with the ability to build bridges between seemingly disparate perspectives, a skill I consider invaluable in today's increasingly interconnected world. It is important to note that these experiences have not only shaped my identity but have also fueled my desire to pursue a career that celebrates and champions diversity. I am confident that this background will continue to enrich my academic and personal journey.""",

"""My involvement in student government has been one of the most rewarding aspects of my high school experience. Serving as class president taught me invaluable lessons about leadership, accountability, and the power of collaborative problem-solving. Throughout my tenure, I worked tirelessly to advocate for my peers, organizing initiatives that addressed key concerns within our school community. Additionally, this role underscored the importance of active listening and consensus-building in effective governance. These experiences have not only strengthened my commitment to public service but have also solidified my aspiration to pursue a career dedicated to civic engagement and social change.""",

"""Since childhood, I have harbored an unwavering passion for storytelling, one that has manifested itself through my love of both reading and creative writing. This passion has served as a constant source of inspiration, allowing me to explore complex themes and diverse perspectives through the written word. Moreover, writing has taught me the importance of patience and perseverance, as crafting a compelling narrative often requires countless revisions. It is a testament to the transformative power of language that a single story can illuminate the human experience in ways that resonate universally. I am eager to continue honing this craft throughout my academic career and beyond.""",

"""Participating in my school's model United Nations program has been an incredibly enriching experience that has broadened my understanding of global affairs. Through rigorous research and impassioned debate, I have developed a nuanced appreciation for the complexities inherent in international diplomacy. Furthermore, this experience has underscored the critical importance of compromise and collaboration in addressing pressing global challenges. It has also instilled in me a deep sense of civic responsibility, one that extends beyond the borders of my own community. As I look ahead, I am eager to continue exploring these themes through further study in international relations.""",

"""My experience as a peer mentor has been a profound testament to the transformative power of guidance and support. Working closely with younger students, I have witnessed firsthand the impact that a caring mentor can have on a young person's confidence and academic trajectory. This role has taught me invaluable lessons about patience, empathy, and effective communication. Moreover, it has reinforced my belief in the power of community to uplift and empower its members. It is through these meaningful connections that I have come to understand the true essence of leadership: not authority, but service to others.""",

"""Overcoming my initial fear of public speaking has been one of the most significant personal challenges I have faced. Through consistent practice and unwavering determination, I have transformed what was once a source of anxiety into a genuine strength. This journey has taught me invaluable lessons about resilience and the importance of stepping outside one's comfort zone. Furthermore, it has underscored the profound connection between vulnerability and growth. Each speech I deliver serves as a reminder that true confidence is not the absence of fear, but the courage to persevere despite it. I look forward to continuing to embrace new challenges in the future.""",

"""My passion for coding began with a simple curiosity about how technology shapes our everyday lives. Over time, this curiosity blossomed into a genuine dedication to computer science, one that has been nurtured through countless hours of independent study and hands-on projects. This journey has not only sharpened my technical skills but has also cultivated a deep appreciation for problem-solving and logical reasoning. Moreover, it has underscored the importance of perseverance when confronting complex challenges. As I look toward the future, I am eager to continue exploring the boundless possibilities that technology offers, driven by an unwavering passion for innovation.""",

"""Serving as editor-in-chief of my school newspaper has been an incredibly formative experience, one that has shaped both my writing and leadership abilities. This role required me to balance journalistic integrity with the practical demands of managing a diverse team of contributors. Furthermore, it taught me the importance of clear communication and constructive feedback in fostering a collaborative environment. It is a testament to the power of dedicated teamwork that our publication was able to consistently deliver high-quality content despite numerous challenges. This experience has solidified my aspiration to pursue a career in journalism, one dedicated to truth and accountability.""",

"""My journey as a competitive swimmer has instilled in me a profound appreciation for discipline, resilience, and the relentless pursuit of excellence. Balancing rigorous training schedules with academic responsibilities has taught me invaluable lessons about time management and perseverance. Moreover, the countless hours spent in the pool have underscored the importance of setting incremental goals in achieving long-term success. It is through this journey that I have come to understand that true growth often emerges from failure just as much as from victory. I am eager to carry these lessons forward as I continue to pursue excellence, both in and out of the water.""",

"""Participating in my school's science fair has been a defining experience that solidified my passion for scientific inquiry. Developing my project required countless hours of research, experimentation, and revision, each step teaching me the importance of patience and methodical thinking. Additionally, this experience underscored the value of resilience in the face of unexpected setbacks, as several of my initial hypotheses proved incorrect. It is through this iterative process that I came to appreciate the true nature of scientific discovery: not a linear path to an answer, but a boundless journey of curiosity. I look forward to continuing this journey throughout my academic career.""",

"""My role as captain of the varsity soccer team has taught me invaluable lessons about leadership, teamwork, and perseverance. Balancing the responsibilities of captaincy with academic demands required careful time management and unwavering dedication. Moreover, this experience underscored the importance of leading by example, particularly during moments of adversity on and off the field. It is a testament to the power of collective effort that our team was able to overcome numerous challenges throughout the season. These lessons in resilience and collaboration will undoubtedly serve me well as I continue to pursue both athletic and academic excellence in the years ahead.""",

"""Growing up with a learning disability presented significant challenges throughout my academic journey, yet it has also been an invaluable source of personal growth. Navigating these obstacles taught me the importance of self-advocacy and resilience in the face of adversity. Furthermore, this experience deepened my empathy for others facing similar struggles, inspiring me to become a mentor for younger students with learning differences. It is a testament to the power of perseverance that I have not only overcome these challenges but have thrived academically despite them. I am confident that these lessons will continue to shape my journey moving forward.""",

"""My participation in the annual charity fundraiser has profoundly shaped my understanding of community service and civic responsibility. Organizing this event required extensive collaboration with local businesses, dedicated volunteers, and passionate community members. This experience taught me invaluable lessons about leadership, communication, and the power of collective action in effecting meaningful change. Moreover, it underscored the importance of empathy and genuine connection in mobilizing others toward a common goal. It is a testament to the strength of community that we were able to exceed our fundraising target, raising crucial funds for a cause I hold close to my heart.""",
]

HUMAN_TEST = [
"""I taught myself to fix bikes off YouTube videos, mostly because I couldn't afford to keep paying the shop downtown. The first derailleur I adjusted, I actually made worse, some cable tension thing I didn't understand yet, and had to bring it in anyway, a little embarrassed. The guy at the shop showed me what I'd done wrong instead of just fixing it silently, which I appreciated more than he probably knows. I've fixed maybe a dozen bikes since then for neighbors, usually for free, sometimes for pizza. I'm not sure I'm good enough to do it professionally. But I like the specific kind of quiet that happens when I'm working on something with my hands and nothing else.""",

"""My mom and I fought constantly the year she went back to school for her nursing degree, mostly over dumb stuff, whose turn it was to make dinner, why the laundry wasn't done. Looking back I think we were both just exhausted and taking it out on the nearest person. She graduated the spring of my junior year, and I watched her walk across that stage prouder than I expected to feel given how much we'd argued that year. I don't think either of us apologized directly for any specific fight. We just started cooking dinner together again, which was its own kind of apology, I guess.""",

"""I've been the only kid in my friend group who doesn't drink, which sounds like it should be a bigger deal than it actually is, most weekends. Mostly people forget, honestly, until someone hands me something and I say no thanks, and then there's this small awkward beat before the conversation moves on. I don't have a dramatic reason. I just don't like how it makes me feel, and it turns out that's allowed to be enough of a reason, even though I spent most of freshman year assuming I needed a better one to give people.""",

"""My chemistry teacher assigns lab partners alphabetically, which is how I ended up working with a kid I'd actively avoided since sixth grade over a stupid disagreement I don't even fully remember the cause of anymore. Six months of shared lab benches later, we're not exactly close, but we've got a working rhythm, he handles the calculations, I handle not spilling things, and I've stopped actively dreading the days we have lab together. I don't think this is a redemption story exactly. It's more that grudges are hard to maintain when you have to share a bunsen burner twice a week.""",

"""I spent last summer working the night shift stocking shelves at the grocery store, which messed up my sleep schedule in ways I'm still not fully recovered from. There's something strange about a grocery store at 2am, empty except for two other employees and whoever's buying ice cream for reasons they don't explain. I got weirdly attached to the routine of it, the specific order you're supposed to face the cereal boxes, the guy who restocked produce next to me who'd worked there eleven years and had opinions about every brand of canned soup. I didn't love the job. I think I'll miss it a little anyway.""",

"""My younger sister was diagnosed with type 1 diabetes when she was seven, and I remember being more scared than she seemed to be, which felt backwards at the time. I learned to count carbs for her lunches before I really understood fractions properly in math class, which is a weird order to learn things in. She's twelve now and manages most of it herself, better than I probably would in her position. I still check her blood sugar app more than she'd probably like, out of habit more than necessity at this point. Old fears are apparently slow to update even after the facts change.""",

"""I quit the swim team after four years, right before what would have been my senior season, and a lot of people had opinions about that decision that I didn't ask for. The truth is less dramatic than people wanted it to be. I just didn't love it anymore, and I'd been pretending otherwise for about a year before I admitted it to myself. I picked up rock climbing instead, which I'm mediocre at, genuinely mediocre, not falsely modest. I think I needed to be bad at something new for a while, after being pretty good at one thing for so long.""",

"""My dad and I built a treehouse the summer before I started high school, using instructions from a book that was clearly written for someone with more tools than we had. We improvised a lot. The ladder is slightly crooked in a way that still bothers him every time he looks at it, though I've never once noticed it climbing up. It took us most of the summer, longer than either of us expected, mostly because we kept stopping to argue about measurements neither of us was actually qualified to be arguing about. It's still standing, four years later. I think that's the part that matters.""",
]

AI_TEST = [
"""My commitment to academic excellence has been a defining characteristic throughout my educational journey. From a young age, I have consistently demonstrated a strong work ethic and an unwavering dedication to achieving my goals. Whether through rigorous coursework or extracurricular pursuits, I have continually sought opportunities for intellectual growth. Moreover, these experiences have taught me invaluable lessons about resilience and perseverance in the face of challenges. It is through this relentless pursuit of knowledge that I have come to understand the true value of education, not merely as a means to an end, but as a lifelong journey of discovery and self-improvement.""",

"""Participating in my community's annual food drive has been an incredibly humbling experience that reshaped my understanding of service and generosity. Coordinating volunteers and donations required extensive organizational skills as well as genuine empathy for those facing food insecurity. This experience underscored the profound impact that collective action can have in addressing systemic challenges within our community. Furthermore, it deepened my appreciation for the resilience of individuals navigating difficult circumstances. It is a testament to the power of community that we were able to provide meaningful support to countless families, an experience that will continue to shape my commitment to service.""",

"""My fascination with astronomy began during a family camping trip, when I first gazed upon the vast expanse of the night sky. This experience ignited a lifelong passion for understanding the mysteries of the universe. Since then, I have dedicated countless hours to studying astrophysics, both through independent research and formal coursework. Moreover, this pursuit has taught me the importance of intellectual curiosity and perseverance in the face of complex, often unanswerable questions. It is a testament to the boundless nature of scientific inquiry that even our most advanced understanding of the cosmos leaves room for wonder. I eagerly anticipate continuing this exploration in college.""",

"""Serving as president of my school's environmental club has been a profoundly rewarding leadership experience. Under my guidance, our club successfully implemented several sustainability initiatives, including a comprehensive recycling program and an annual campus clean-up event. This role has taught me invaluable lessons about organizational leadership, effective communication, and the power of grassroots activism. Additionally, it has underscored the critical importance of environmental stewardship in addressing the pressing challenges of climate change. It is through this work that I have come to understand that meaningful change often begins at the local level, a lesson I intend to carry with me throughout my future endeavors.""",

"""My passion for creative writing has been a constant thread throughout my academic journey, shaping both my intellectual curiosity and personal identity. Through countless hours spent crafting short stories and poetry, I have developed not only my technical writing skills but also a deeper understanding of the human condition. Moreover, this creative pursuit has taught me the importance of vulnerability and authenticity in artistic expression. It is a testament to the transformative power of storytelling that even our most personal narratives can resonate universally with others. I am eager to continue honing this craft as I pursue further study in literature and creative writing.""",

"""Overcoming the challenges of being a first-generation college applicant has profoundly shaped my resilience and determination. Navigating the complexities of the college application process without the guidance of family experience required significant self-advocacy and resourcefulness. This journey has taught me invaluable lessons about perseverance in the face of systemic obstacles. Furthermore, it has deepened my commitment to paving the way for other first-generation students in my community. It is a testament to the power of determination that I have been able to overcome these challenges, and I look forward to continuing this journey of growth and achievement in college.""",

"""My involvement in competitive chess has taught me invaluable lessons about strategic thinking, patience, and resilience. Years of rigorous practice and tournament competition have not only sharpened my analytical skills but also instilled in me a deep appreciation for the value of foresight and careful planning. Moreover, this pursuit has underscored the importance of learning from failure, as even the most skilled players inevitably encounter setbacks. It is through this iterative process of growth that I have come to understand chess not merely as a game, but as a profound metaphor for navigating life's complex challenges. I look forward to continuing this journey of intellectual growth.""",

"""My experience studying abroad in a small rural village fundamentally transformed my perspective on global citizenship and cultural understanding. Immersing myself in an unfamiliar culture required significant adaptability and open-mindedness, qualities that have since become central to my identity. This experience underscored the profound value of stepping outside one's comfort zone in fostering genuine personal growth. Furthermore, it deepened my appreciation for the rich diversity of human experience across different cultural contexts. It is a testament to the transformative power of travel that this brief experience continues to shape my worldview and academic aspirations in profound and lasting ways.""",
]

ESL_TEST = [
"""When I come to America I am eleven years old and I know maybe fifty words in English. My mother tell me every day, you must study hard, education is the only thing nobody can take from you. I remember this every time. In my country we did not have this opportunity so easy, my parents work very hard for this chance. I study English three hours every night after homework, I write same sentences many times until I remember. My teacher is very patient with me, she stay after school many days to help. Now I am not afraid to speak in class anymore, this is big change for me. I want to become doctor because in my village there was no doctor close by and my grandmother died because hospital was too far.""",

"""My family come to this country when I was seven years, we leave everything behind, our house, our relatives, all our friends. First year is very hard, I don't understand teacher, I don't understand other students, everything is confuse to me. But my father always say, hard work is more important than talent, you must never give up even when it is difficult. I believe this very much. Every day after school I help my mother in her small store, I learn how to talk to customer, how to count money fast, how to solve problem when something go wrong. This job teach me many thing that school cannot teach. I want to study business so I can help my parents' store grow bigger and also help other immigrant family like mine.""",

"""I think my biggest challenge is not academic subject but is speaking up in class. In my country, student must respect teacher and not ask too much question, this is normal there. Here is very different, teacher want you to talk, to argue, to say your opinion even if it is wrong opinion. First semester I say almost nothing in class, I am too scared my English is not good enough and other student will laugh. My English teacher notice this and one day she ask me to stay after class, not to punish me but to encourage me, she say my writing show I have good idea, I just need practice speaking them. Slowly I start to raise my hand, first only when I am very sure, later even when I am not sure. This small change is very important for me because it show me I can grow even in the thing that scare me most.""",
]

MIXED_DEMO = """I spent the summer before junior year working the fryer station at a diner two towns over, mostly because it was the only job that would take someone who couldn't drive yet and needed a ride from her aunt. The kitchen was loud in a way I didn't expect, not just the sizzling, but the cooks yelling order numbers over each other, the dishwasher going the whole time, someone's radio playing something I never quite identified. I burned my wrist twice in the first two weeks and the head cook, a guy named Ray who'd worked there nineteen years, didn't say much about it except to hand me the burn cream and tell me where the timer was.

This experience taught me invaluable lessons about perseverance and the importance of hard work in the face of adversity. Through this journey, I came to understand that true growth often emerges from stepping outside one's comfort zone. Moreover, working alongside dedicated colleagues like Ray underscored the profound value of mentorship and collaborative teamwork in any professional setting. It is a testament to the transformative power of adversity that a single summer job could shape my understanding of discipline and resilience so significantly. As I look toward the future, I remain committed to carrying these lessons forward into every challenge that lies ahead."""
